{% set name = "pint-pal" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pint_pal-{{ version }}.tar.gz
  sha256: 2233094d49398fe74fb06a1aa940610c741ca3eb717dc67c0b1a102f3d3dd8f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - versioneer ==0.28
    - versioneer
    - pip
  run:
    - python >={{ python_min }}
    - ruamel.yaml
    - pint-pulsar >=0.9.1
    - enterprise-pulsar >=3.3.2
    - enterprise_extensions >=v2.4.1
    - pytest
    - nbconvert
    - ipywidgets >=7.6.3
    - pypulse >=0.0.1
    - numpy
    - weasyprint
    - pytest-xdist >=2.3.0
    - jupyter
    - seaborn
    - gitpython

test:
  requires:
    - python {{ python_min }}
  imports:
    - pint_pal

about:
  home: https://pypi.org/project/pint-pal/
  summary: A long-lived repository for NANOGrav Pulsar Timing analysis work.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AaronDJohnson
    - JPGlaser
    - gooddc
    - swiggumj
    - tcromartie
