{% set name = "pint-pal" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pint_pal-{{ version }}.tar.gz
  sha256: d39065d0cbdb210f80d295e419322286892ff35069caa978fe9db891176286b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - versioneer ==0.28
    - versioneer
    - pip
  run:
    - python >=3.8
    - ruamel.yaml
    - pint-pulsar >=0.9.1
    - enterprise-pulsar >=3.3.2
    - enterprise_extensions >=v2.4.1
    - pytest
    - nbconvert
    - ipywidgets >=7.6.3
    - pypulse >=0.0.1
    - numpy
    - weasyprint
    - pytest-xdist >=2.3.0
    - jupyter
    - seaborn
    - gitpython

test:
  imports:
    - pint_pal

about:
  home: https://pypi.org/project/pint-pal/
  summary: A long-lived repository for NANOGrav Pulsar Timing analysis work.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AaronDJohnson
    - JPGlaser
    - gooddc
    - swiggumj
    - tcromartie
